### ISSUE TITLE
Remove defaults from app config files

### ISSUE THREAD

**Issue by kipparker** [icebreakerone/perseus-demo-energy#35]
The default values in app configuration [authentication/api/conf.py](https://github.com/icebreakerone/perseus-demo-energy/blob/main/authentication/api/conf.py) are causing confusion. We should remove them so the app will not load without a valid .env file. Instructions for correct values and a .env.template file are already available.

**Comment by padajo** [comment]
My suggestion would be to update the README to specify that they need to specify all the secrets in their environment.
https://docs.docker.com/compose/compose-file/09-secrets/
e.g.
```
secrets:
  oauth_client_id:
    environment: "OAUTH_CLIENT_ID"
  client_id:
    environment: "CLIENT_ID"
```
and so on...
